"""add dossier tables

Revision ID: 29505a396dd9
Revises: ae567a781f13
Create Date: 2026-09-27 17:48:03.005367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29505a396dd9'
down_revision: Union[str, Sequence[str], None] = 'ae567a781f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    op.create_table('dossier_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('module_number', sa.String(length=20), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_modules_dossier_id'), 'dossier_modules', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_dossier_modules_id'), 'dossier_modules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dossier_modules_id'), table_name='dossier_modules')
    op.drop_index(op.f('ix_dossier_modules_dossier_id'), table_name='dossier_modules')
    op.drop_table('dossier_modules')
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
