"""add leave approval audit fields

Revision ID: 9e62dbaa66fe
Revises: 52bab153ac14
Create Date: 2026-09-24 15:44:21.537476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e62dbaa66fe'
down_revision: Union[str, Sequence[str], None] = '52bab153ac14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('leaves', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leaves', sa.Column('rejected_by', sa.Integer(), nullable=True))
    op.add_column('leaves', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'leaves', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leaves', 'users', ['rejected_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'rejected_at')
    op.drop_column('leaves', 'rejected_by')
    op.drop_column('leaves', 'approved_at')
    op.drop_column('leaves', 'approved_by')
    # ### end Alembic commands ###
