import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { leaveService, leaveTypeService } from '../services/leaveService';

export default function NewLeavePage(){
 const nav=useNavigate(),[types,setTypes]=useState([]),[form,setForm]=useState({leave_type_id:'',start_date:'',end_date:'',reason:''}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{leaveTypeService.list().then(setTypes).catch(e=>setError(e?.response?.data?.detail||'Could not load leave types.'))},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setError('');if(!form.leave_type_id||!form.start_date||!form.end_date){setError('Leave type, start date and end date are required.');return}if(form.start_date>form.end_date){setError('Start date cannot be after end date.');return}setLoading(true);try{const leave=await leaveService.create({...form,leave_type_id:Number(form.leave_type_id)});nav(`/leaves/${leave.id}`)}catch(e){setError(e?.response?.data?.detail||e?.message||'Could not create leave.')}finally{setLoading(false)}};
 return <div className="page narrow-page"><div className="page-title"><div><p className="eyebrow">New request</p><h1>Apply for leave</h1><p>The API initially creates the application as a draft.</p></div><Link to="/leaves" className="ghost-btn">Back</Link></div><section className="panel form-panel"><form onSubmit={submit}>{error&&<div className="alert">{error}</div>}<label>Leave type<select name="leave_type_id" value={form.leave_type_id} onChange={change}><option value="">Select leave type</option>{types.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.total_days} days/year</option>)}</select></label><div className="form-grid"><label>Start date<input type="date" name="start_date" value={form.start_date} onChange={change}/></label><label>End date<input type="date" name="end_date" value={form.end_date} onChange={change}/></label></div><label>Reason <span className="muted">(optional)</span><textarea name="reason" rows="5" maxLength="2000" value={form.reason} onChange={change} placeholder="Add context for your request…"/></label><div className="form-actions"><Link to="/leaves" className="ghost-btn">Cancel</Link><button className="primary-btn" disabled={loading}>{loading?'Creating…':'Create draft'}</button></div></form></section></div>;
}
